#!/bin/sh
# place this file in .git/hooks

echo "analyzing"

./gradlew ktlintCheck detekt

status=$?

if [ "$status" = 0 ] ; then
    echo "no issues"
    exit 0
else
    echo 1>&2 "issue found, commit aborted"
    # open detekt report with chrome browser
    open -a "Google Chrome" "/Users/kakao/AndroidStudioProjects/android-conference-app/app/build/reports/detekt/detekt.html"
    # open ktlint report with chrome browser
    open -a "Google Chrome" "/Users/kakao/AndroidStudioProjects/android-conference-app/app/build/reports/ktlint/ktlintMainSourceSetCheck/ktlintMainSourceSetCheck.xml"

    exit 1
fi